#!/usr/bin/env ruby
# Simple script to push to multiple git remotes and branches with or without tags
# Command: gitpush
# Args: remote1 remote2 remote3 [(-b or --branches) branch1 branch2]* [(-t or --tags)]
# Example: gitpush remote1 remote2 remote3 [(-b or --branches) branch1 branch2]* [(-t or --tags)]

class String
  def colorize(color_code) "\e[#{color_code}m#{self}\e[0m" end
  def red; colorize(31) end
  def green; colorize(32) end
  def yellow; colorize(33) end
end

remotes, branches = Array.new, Array.new
tags, mult_branch = false, false

ARGV.each do|a|
  if a == "-t" or a == "--tags" and tags == false
    tags = true
  elsif a == "-b" or a == "--branches" and mult_branch == false
    mult_branch = true
  elsif mult_branch
    branches << a
  else
    remotes << a
  end
end

branches << "master" unless mult_branch

for j in 0..(remotes.count-1)
  for i in 0..(branches.count-1)
    cmd = "git push #{remotes[j]} #{branches[i]}"
    cmd += " --tags" if tags
    puts "Pushing branch \"#{branches[i]}\" to remote \"#{remotes[j]}\"".yellow
    puts system(cmd) ? "Push successful".green : "Push failed!".red 
  end
end
