#!/usr/bin/env ruby
#This script is the math behind how XD6s name was created (Haxxed and Nexus were the names used)

class String
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end
  def red
    colorize(31)
  end
  def green
    colorize(32)
  end
  def yellow
    colorize(33)
  end
  def cyan
    colorize(36)
  end
  def bold
    "\e[1m#{self}\e[0m"
  end
end

require 'active_support/core_ext/integer/inflections'

print "Enter number of people: ".yellow
count = gets.to_i
names = 0

for i in 1..count
  print "Enter the ".yellow + "#{i.ordinalize.bold.yellow}" + " person's name: ".yellow
  names += gets.downcase.getbyte(0)
end

group_name = "|  ".red + "Group Name: ".bold.yellow + "x#{names.to_s(16).upcase}".cyan + "  |".red
group_name_len = group_name.length - ("".bold.yellow.cyan.red.red.length) #Hacks #YOLO
bar = "=".red * group_name_len

puts "#{bar}\n#{group_name}\n#{bar}"
