#!/bin/sh
#A simple script to clean out a directory except for the files you wish to save
#Usage: rme file1 file2 file3

for file in "$@"
  do
    mv -v  $file ..
  done
rm -rv *
for file in "$@"
  do
    mv -v ../$file .
  done
